## Prepare the Data for Machine Learning Algorithms

### Source: Hands-On Machine Learning with Scikit-Learn and TensorFlow, Aurélien Geron, O'Reilly
https://github.com/ageron/handson-ml

In [28]:
import numpy as np
import pandas as pd

# Load housing data for California districts
housing = pd.read_csv('datasets/housing.csv')
housing.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [29]:
# stratify data by a new column 'income_category'
housing["income_cat"] = pd.cut(housing["median_income"],
                               bins=[0., 1.5, 3.0, 4.5, 6., np.inf],
                               labels=[1, 2, 3, 4, 5])
housing.shape

(20640, 11)

In [30]:
# split the data into training and test sets
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing, housing["income_cat"]):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]

## Prepare the data for Machine Learning algorithms

In [31]:
housing = strat_train_set.drop("median_house_value", axis=1) # drop labels for training set
housing_labels = strat_train_set["median_house_value"].copy() # this is what we are trying to predict!

## Data cleaning

In [32]:
# total_bedrooms attribute has some missing values
housing[housing['total_bedrooms'].isna()].head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
4629     -118.30     34.07                18.0       3759.0             NaN   
6068     -117.86     34.01                16.0       4632.0             NaN   
17923    -121.97     37.35                30.0       1955.0             NaN   
13656    -117.30     34.05                 6.0       2155.0             NaN   
19252    -122.79     38.48                 7.0       6837.0             NaN   

       population  households  median_income ocean_proximity income_cat  
4629       3296.0      1462.0         2.2708       <1H OCEAN          2  
6068       3038.0       727.0         5.1762       <1H OCEAN          4  
17923       999.0       386.0         4.6328       <1H OCEAN          4  
13656      1039.0       391.0         1.6675          INLAND          2  
19252      3468.0      1405.0         3.1662       <1H OCEAN          3

In [33]:
# option 1: Get rid of the corresponding districts
housing.dropna(subset=['total_bedrooms'])

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
17606    -121.89     37.29                38.0       1568.0           351.0   
18632    -121.93     37.05                14.0        679.0           108.0   
14650    -117.20     32.77                31.0       1952.0           471.0   
3230     -119.61     36.31                25.0       1847.0           371.0   
3555     -118.59     34.23                17.0       6592.0          1525.0   
...          ...       ...                 ...          ...             ...   
6563     -118.13     34.20                46.0       1271.0           236.0   
12053    -117.56     33.88                40.0       1196.0           294.0   
13908    -116.40     34.09                 9.0       4855.0           872.0   
11159    -118.01     33.82                31.0       1960.0           380.0   
15775    -122.45     37.77                52.0       3095.0           682.0   

       population  households  median_income ocean_proximity income_cat  
17606       710.0       339.0         2.7042       <1H OCEAN          2  
18632       306.0       113.0         6.4214       <1H OCEAN          5  
14650       936.0       462.0         2.8621      NEAR OCEAN          2  
3230       1460.0       353.0         1.8839          INLAND          2  
3555       4459.0      1463.0         3.0347       <1H OCEAN          3  
...           ...         ...            ...             ...        ...  
6563        573.0       210.0         4.9312          INLAND          4  
12053      1052.0       258.0         2.0682          INLAND          2  
13908      2098.0       765.0         3.2723          INLAND          3  
11159      1356.0       356.0         4.0625       <1H OCEAN          3  
15775      1269.0       639.0         3.5750        NEAR BAY          3  

[16354 rows x 10 columns]

In [34]:
# option 2: Get rid of the whole attribute
housing.drop('total_bedrooms', axis=1)

longitude  latitude  housing_median_age  total_rooms  population  \
17606    -121.89     37.29                38.0       1568.0       710.0   
18632    -121.93     37.05                14.0        679.0       306.0   
14650    -117.20     32.77                31.0       1952.0       936.0   
3230     -119.61     36.31                25.0       1847.0      1460.0   
3555     -118.59     34.23                17.0       6592.0      4459.0   
...          ...       ...                 ...          ...         ...   
6563     -118.13     34.20                46.0       1271.0       573.0   
12053    -117.56     33.88                40.0       1196.0      1052.0   
13908    -116.40     34.09                 9.0       4855.0      2098.0   
11159    -118.01     33.82                31.0       1960.0      1356.0   
15775    -122.45     37.77                52.0       3095.0      1269.0   

       households  median_income ocean_proximity income_cat  
17606       339.0         2.7042       <1H OCEAN          2  
18632       113.0         6.4214       <1H OCEAN          5  
14650       462.0         2.8621      NEAR OCEAN          2  
3230        353.0         1.8839          INLAND          2  
3555       1463.0         3.0347       <1H OCEAN          3  
...           ...            ...             ...        ...  
6563        210.0         4.9312          INLAND          4  
12053       258.0         2.0682          INLAND          2  
13908       765.0         3.2723          INLAND          3  
11159       356.0         4.0625       <1H OCEAN          3  
15775       639.0         3.5750        NEAR BAY          3  

[16512 rows x 9 columns]

In [35]:
# option 3: set the missing value to some value, like zero, mean or median
median = housing['total_bedrooms'].median()
housing['total_bedrooms'].fillna(median, inplace=True)

### Let's use SimpleImputer to fill in missing values with the median

In [36]:
# Scikit-Learn provides a class to take care of missing values: Imputer
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")

In [37]:
# First, create a copy of data without categorical data
housing_num = housing.drop('ocean_proximity', axis=1)

In [38]:
# Fit the imputer instance to the training data, this does not change the data yet
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [39]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2119.5   ,  433.    , 1164.    ,
        408.    ,    3.5409,    3.    ])

In [40]:
# Now replace missing values with the medians, using this 'trained' imputer
X = imputer.transform(housing_num)
X

array([[-121.89  ,   37.29  ,   38.    , ...,  339.    ,    2.7042,
           2.    ],
       [-121.93  ,   37.05  ,   14.    , ...,  113.    ,    6.4214,
           5.    ],
       [-117.2   ,   32.77  ,   31.    , ...,  462.    ,    2.8621,
           2.    ],
       ...,
       [-116.4   ,   34.09  ,    9.    , ...,  765.    ,    3.2723,
           3.    ],
       [-118.01  ,   33.82  ,   31.    , ...,  356.    ,    4.0625,
           3.    ],
       [-122.45  ,   37.77  ,   52.    , ...,  639.    ,    3.575 ,
           3.    ]])

In [41]:
type(X)

numpy.ndarray

In [42]:
# convert this numpy array back to a data frame
housing_tr = pd.DataFrame(X, columns=housing_num.columns)
housing_tr.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.89     37.29                38.0       1568.0           351.0   
1    -121.93     37.05                14.0        679.0           108.0   
2    -117.20     32.77                31.0       1952.0           471.0   
3    -119.61     36.31                25.0       1847.0           371.0   
4    -118.59     34.23                17.0       6592.0          1525.0   

   population  households  median_income  income_cat  
0       710.0       339.0         2.7042         2.0  
1       306.0       113.0         6.4214         5.0  
2       936.0       462.0         2.8621         2.0  
3      1460.0       353.0         1.8839         2.0  
4      4459.0      1463.0         3.0347         3.0

## Note: this material is beyond the scope of this course and meant only as a motivation for further learning

In [43]:
from sklearn.preprocessing import FunctionTransformer

# get the right column indices: safer than hard-coding indices 3, 4, 5, 6
rooms_ix, bedrooms_ix, population_ix, household_ix = [
    list(housing.columns).index(col)
    for col in ("total_rooms", "total_bedrooms", "population", "households")]

def add_extra_features(X, add_bedrooms_per_room=True):
    rooms_per_household = X[:, rooms_ix] / X[:, household_ix]
    population_per_household = X[:, population_ix] / X[:, household_ix]
    if add_bedrooms_per_room:
        bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
        return np.c_[X, rooms_per_household, population_per_household,
                     bedrooms_per_room]
    else:
        return np.c_[X, rooms_per_household, population_per_household]

attr_adder = FunctionTransformer(add_extra_features, validate=False,
                                 kw_args={"add_bedrooms_per_room": False})
housing_extra_attribs = attr_adder.fit_transform(housing.values)

## Now let's build a pipeline for preprocessing the numerical attributes:
- Handle missing values
- Add extra features
- Scale values to 0-1 range

In [44]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy="median")),
        ('attribs_adder', FunctionTransformer(add_extra_features, validate=False)),
        ('std_scaler', StandardScaler()),
    ])

housing_num_tr = num_pipeline.fit_transform(housing_num)
housing_num_tr

array([[-1.15604281,  0.77194962,  0.74333089, ..., -0.31205452,
        -0.08649871,  0.15531753],
       [-1.17602483,  0.6596948 , -1.1653172 , ...,  0.21768338,
        -0.03353391, -0.83628902],
       [ 1.18684903, -1.34218285,  0.18664186, ..., -0.46531516,
        -0.09240499,  0.4222004 ],
       ...,
       [ 1.58648943, -0.72478134, -1.56295222, ...,  0.3469342 ,
        -0.03055414, -0.52177644],
       [ 0.78221312, -0.85106801,  0.18664186, ...,  0.02499488,
         0.06150916, -0.30340741],
       [-1.43579109,  0.99645926,  1.85670895, ..., -0.22852947,
        -0.09586294,  0.10180567]])

In [45]:
# Add to the pipeline a OneHotEncoder
from sklearn.compose import ColumnTransformer

In [46]:
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", OneHotEncoder(), cat_attribs),
    ])

housing_prepared = full_pipeline.fit_transform(housing)

In [47]:
housing_prepared

array([[-1.15604281,  0.77194962,  0.74333089, ...,  0.        ,
         0.        ,  0.        ],
       [-1.17602483,  0.6596948 , -1.1653172 , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.18684903, -1.34218285,  0.18664186, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 1.58648943, -0.72478134, -1.56295222, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.78221312, -0.85106801,  0.18664186, ...,  0.        ,
         0.        ,  0.        ],
       [-1.43579109,  0.99645926,  1.85670895, ...,  0.        ,
         1.        ,  0.        ]])

## Select and train a model

In [48]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(housing_prepared, housing_labels) # THIS IS WHERE THE MAGIC HAPPENS!

LinearRegression()

In [49]:
# let's try the full preprocessing pipeline on a few training instances
some_data = housing.iloc[:5]
some_labels = housing_labels.iloc[:5]
some_data_prepared = full_pipeline.transform(some_data)

# print("Predictions:", lin_reg.predict(some_data_prepared))

In [50]:
print("Labels:", list(some_labels))

Labels: [286600.0, 340600.0, 196900.0, 46300.0, 254500.0]


In [51]:
# predict median house value based on one sample input district
longitude           = -121.33
latitude            = 38.65
housing_median_age  = 23
total_rooms         = 5000
total_bedrooms      = 5000
population          = 10000
households          = 6000
median_income       = 2
ocean_proximity     = 'INLAND'
income_cat          = 2

my_data = pd.DataFrame([[longitude, latitude, housing_median_age, total_rooms, total_bedrooms, 
            population, households, median_income, ocean_proximity, income_cat]],
                      columns=['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 
            'population', 'households', 'median_income', 'ocean_proximity', 'income_cat'])
my_data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.33     38.65                  23         5000            5000   

   population  households  median_income ocean_proximity  income_cat  
0       10000        6000              2          INLAND           2

In [52]:
my_data_prepared = full_pipeline.transform(my_data)
lin_reg.predict(my_data_prepared)

array([590968.70175221])

In [53]:
# This predicts a median house value of 590968 for the given input!

## Note: this is only the beginning. The model needs to be tested and fine-tuned. This is material for another course!