In [28]:
import numpy as np

### indexing arrays with numpy.newaxis
https://numpy.org/doc/stable/reference/constants.html?highlight=newaxis#numpy.newaxis

In [29]:
a = np.array([3, 1, 2])
b = np.array([10, 8, 9])

In [30]:
an = a[:, np.newaxis]
an # shape (3, 1)

array([[3],
       [1],
       [2]])

In [31]:
bn = b[np.newaxis, :]
bn # shape (1, 3)

array([[10,  8,  9]])

In [42]:
# notice how addition is broadcast
cn = an + bn
cn

array([[13, 11, 12],
       [11,  9, 10],
       [12, 10, 11]])

In [33]:
an - bn

array([[-7, -5, -6],
       [-9, -7, -8],
       [-8, -6, -7]])

In [36]:
# sum list element values
cn.sum(-1)

array([36, 30, 33])