### Fixed-Type Arrays in Python

In [1]:
import array
L = list(range(10))
A = array.array('i', L) # 'i' is the type code for integer
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

The Python array object provides more efficient storage of array-based data.

NumPy adds to this efficient operations on data

### Creating NumPy arrays from Python lists

In [3]:
import numpy as np

np.array([1, 3, 4, 5, 9, 7])

array([1, 3, 4, 5, 9, 7])

In [4]:
# Explicitly set data type
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

### NumPy arrays can be multidimensional (list of lists)

In [6]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating arrays from scratch

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# 3x5 array of floating point numbers
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# 3x5 array of approx value for pi
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])